source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '~>3.2.0'

gem 'bootsnap', require: false
gem 'groupdate'
gem 'pg', '~> 1.1'
gem 'puma', '~> 6.0'
gem 'rails', '~> 7.1.0'

# Authentication
gem 'bcrypt', '~> 3.1.7'
gem 'jwt'

# CORS
gem 'rack-cors'

# File processing
gem 'caxlsx'
gem 'caxlsx_rails'
gem 'csv'

# Development & Debugging
group :development, :test do
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'pry-rails'
  gem 'rubocop', require: false
  gem 'rubocop-rails', require: false
  gem 'ruby-lsp', require: false
end

group :development do
  # Speed up commands on slow machines / big apps
  # gem "spring"
end
